### ISSUE TITLE
Front-End Upload a Pet TCUP004 Page Upload a Pet

### ISSUE THREAD

**Issue by NichtSylph** [Paul-Austin-Oswego-CSC480-HCI521/OZ-CSC-480-HCI-521-Spring-2024#21]
Entity: Choose Image

Expected Function: When user chooses image to input, image name should appear to indicate as feedback to the user that the image has been selected and is ready to upload
Current: Function: When I select an image, the system does not indicate in any form that the image has been received, and if I click save, the system notifies me that I haven't uploaded an image.

**Comment by SejalRana** [comment]
selected image is displayed
