### ISSUE TITLE
Front End TCSD006 - Shelter Dashboard - Shelter Description

### ISSUE THREAD

**Issue by NichtSylph** [Paul-Austin-Oswego-CSC480-HCI521/OZ-CSC-480-HCI-521-Spring-2024#30]
**High Priority**
Expected: If shelter description is long, it should say "see more" and the description will expand appropriately
Current: If Shelter Description is long, it shows the whole thing horizontally

**Comment by kaylyn-jones** [comment]
Duplicate Report
