### ISSUE TITLE
TCSH001 Shelter Home Page/ Log in & Sign up Buttons

### ISSUE THREAD

**Issue by kaylyn-jones** [Paul-Austin-Oswego-CSC480-HCI521/OZ-CSC-480-HCI-521-Spring-2024#51]
**Medium Priority**
Expected: There should only be 1 log in and 1 sign up button
Current: There are 2 log in and 2 sign up buttons on the same page - Usability bug

**Comment by mthomps9802** [comment]
Issue Resolved
